### PR TITLE
Apply fixed pony compression patches

### LINKED ISSUE #86: Newly Added Manes Editable, but Reset upon Saving.
So I've managed to go through the process of compiling and adding in new manes / back manes to my dev server, and they show up with the proper art and patterns on the selection page, and additionally update their colors correctly. However, I've notced that the game *somewhere* has a possible hardcoded value or specific declaration for how many manes are supposed to be available- I've found that clicking any mane over index of 31 resets the index as if it'd been divided by 31, so the third new mane I've added resets back to the second mane upon saving and entering the game. This also applies to the back manes, however, since there was three less back manes in the original code, three of the new back manes do work perfectly- but the rest past this 31 are reset.  I was wondering if you guys had run into this problem and possibly found where the game has decided 31 is the max it can do ?

### PR DESCRIPTION
**Pull request by Stubenhocker1399**
Fixes issues with more than 32 mane sprites
Courtesy Pony Town Team

This fixes #86

### CODE REVIEW

File: src/ts/common/compressPony.ts [hunk 1]
```diff
@@ -553,18 +559,20 @@ const readNumber = readBits(NUMBERS_BITS);
 export function readPony(read: ReadBits): Precompressed {
 	const version = read(VERSION_BITS);
 
-	if (version > VERSION) {
+	if (version > 5) {
```
Comment (BytewaveMLP) [inline src/ts/common/compressPony.ts]: Though it's not really our code, it's probably better to change this back to `VERSION`. Magic numbers are bad.
